spring:
  application:
    name: fraud-detection-service
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: fraud-detection-service
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer


server:
  port: ${PORT:0}

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instace_id:${random.value}}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

logging:
  level:
    com.fraud.detection: DEBUG
    org.apache.kafka: WARN

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  packages-to-scan: com.fraud.detection.service